### ISSUE TITLE
[ToDo] Case File

### ISSUE THREAD

**Issue by AlbertUnruh** [Alberto-X3/Alberto-X3-V3#37]
At the moment the *Case File* extension doesn't have a feature for results. This should be added.

Also criminal records should be added.

ToDo:
- [ ] add results
- [ ] add criminal records
- [ ] actually implement /edit
- [ ] actually implement /change_status

As an reference:
- in #21 the extension was requested and
- in #22 the extension was merged
